apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cd-manager
  namespace: default
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - services
  - deployments
  - replicasets
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - list
  - get
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-cd-manager-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cd-manager
subjects:
- kind: ServiceAccount
  name: jenkins-agent
  namespace: default